name: 筛选

on:
  push:
    paths:
      - 'active_fund_screener.py'
      - '.github/workflows/fund_screener.yml'
  workflow_dispatch:  # 支持手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'  # 上海时区

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 用于 push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ========================================================
      # ⬇️ 关键修改：直接安装所有依赖，无需 requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy akshare matplotlib openpyxl
      # ⬆️ 关键修改
      # ========================================================

      - name: Run screening script
        run: python active_fund_screener.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add output/ || true
          git commit -m "更新基金筛选结果 - $(date +'%Y-%m-%d %H:%M:%S')" || echo "无新文件变动，跳过 commit"
          git push origin HEAD:${{ github.ref_name }} || echo "无变动，跳过 push"
