name: Scrape Fund Basic Info

# 触发条件
on:
  push:
    paths:
      - 'scrape_funds.py'          # 脚本改动
      - '.github/workflows/scrape.yml'  # workflow 改动
      - 'C类.txt'                  # 代码列表改动（可选）
  workflow_dispatch:               # 手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai            # 上海时区

    permissions:
      contents: write              # 允许 push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_funds.py

      - name: Commit & push CSV (if changed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add fund_data.csv
          git diff --quiet && echo "No changes" && exit 0
          git commit -m "Auto-update fund_data.csv $(date +'%F %T %Z')"
          git push
